### ISSUE TITLE
Can't upload template

### ISSUE THREAD

**Issue by woj-tek** [killbill/killbill-client-java#129]
When trying to upload a template (even default one like the one from the documentation: https://github.com/killbill/killbill/blob/master/util/src/main/resources/org/killbill/billing/util/invoice/templates/HtmlInvoiceTemplate.mustache) I get following exception:

Code is just plain api call with template in string:

```java
invoiceApi.uploadInvoiceTemplate(template, RequestOptions.builder().withCreatedBy("wojtek").build());
```

```
org.killbill.billing.client.KillBillClientException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 2]

	at org.killbill.billing.client.KillBillHttpClient.unmarshalResponse(KillBillHttpClient.java:481)
	at org.killbill.billing.client.KillBillHttpClient.deserializeResponse(KillBillHttpClient.java:410)
	at org.killbill.billing.client.KillBillHttpClient.throwExceptionOnResponseError(KillBillHttpClient.java:387)
	at org.killbill.billing.client.KillBillHttpClient.doPrepareRequestInternal(KillBillHttpClient.java:349)
	at org.killbill.billing.client.KillBillHttpClient.doPrepareRequest(KillBillHttpClient.java:296)
	at org.killbill.billing.client.KillBillHttpClient.doPost(KillBillHttpClient.java:210)
	at org.killbill.billing.client.KillBillHttpClient.doPost(KillBillHttpClient.java:205)
	at org.killbill.billing.client.api.gen.InvoiceApi.uploadInvoiceTemplate(InvoiceApi.java:833)
	at org.killbill.billing.client.api.gen.InvoiceApi.uploadInvoiceTemplate(InvoiceApi.java:812)
…
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2737)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:902)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at org.killbill.billing.client.KillBillHttpClient.unmarshalResponse(KillBillHttpClient.java:469)
	... 76 more
```

btw. it doesn't work from CURL neither with 400 error:

```html
<!doctype html>
<html lang="en">
<head><title>HTTP Status 400 – Bad Request</title>
    <style type="text/css">
        body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}
    </style>
</head>
<body>
    <h1>HTTP Status 400 – Bad Request</h1>
    <hr class="line"/>
    <p><b>Type</b> Status Report</p>
    <p><b>Message</b> Bad Request</p>
    <p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p>
    <hr class="line"/>
    <h3>Apache Tomcat/8.5.91</h3></body>
</html>
```

**Comment by reshmabidikar** [comment]
This works fine at our end. Could you please provide more details (exact cURL used, stacktrace seen) and post a query in the [Kill Bill mailing list](https://groups.google.com/forum/#!forum/killbilling-users)? Closing this ticket for now.
