### ISSUE TITLE
Not able to create basic account  killbill-client-java library

### ISSUE THREAD

**Issue by NickEm** [killbill/killbill-client-java#70]
I encountered issue with creating basic account using this library.
I'm using:
killbill - 0.18.19 (Docker based)
killbill-client-java - 0.41.9

Next peace of code:
```
public static void main(String[] args) throws Exception {
        final KillBillHttpClient killBillHttpClient = new KillBillHttpClient("http://127.0.0.1:8080",
                "admin",
                "password",
                "nick-em",
                "nick-em-secret");
        final KillBillClient killBillClient = new KillBillClient(killBillHttpClient);

        // Create an account
        Account account = new Account();
        account.setName("John Doe");
        account.setEmail("john.doe@example.com");
        account.setCurrency("USD");
        account = killBillClient.createAccount(account, RequestOptions.builder()
                .withCreatedBy("Nick Em")
                .withReason("Test reason")
                .withComment("No comments").build());
    }
```
Always throws:
```
Exception in thread "main" org.killbill.billing.client.KillBillClientException: Unrecognized field "referenceTime" (class org.killbill.billing.jaxrs.json.AccountJson), not marked as ignorable (26 known properties: "firstNameLength", "paymentMethodId", "isMigrated", "accountId", "auditLogs", "name", "isNotifiedForInvoices", "billCycleDayLocal", "accountBalance", "currency", "externalKey", "accountCBA", "country", "postalCode", "timeZone", "locale", "email", "address1", "parentAccountId", "notes", "isPaymentDelegatedToParent", "city", "phone", "state", "company", "address2"])
 at [Source: org.apache.catalina.connector.CoyoteInputStream@62392429; line: 1, column: 517] (through reference chain: org.killbill.billing.jaxrs.json.AccountJson["referenceTime"])
        at org.killbill.billing.client.KillBillHttpClient.throwExceptionOnResponseError(KillBillHttpClient.java:636)
        at org.killbill.billing.client.KillBillHttpClient.doPrepareRequest(KillBillHttpClient.java:501)
        at org.killbill.billing.client.KillBillHttpClient.doPost(KillBillHttpClient.java:247)
        at org.killbill.billing.client.KillBillHttpClient.doPost(KillBillHttpClient.java:242)
        at org.killbill.billing.client.KillBillClient.createAccount(KillBillClient.java:295)
        at com.nick.em.Main.main(Main.java:34)
```
but when I'm using **curl** everything is OK.
 ```
curl -v \
     -u admin:password \
     -H "X-Killbill-ApiKey: nick-em" \
     -H "X-Killbill-ApiSecret: nick-em-secret" \
     -H "Content-Type: application/json" \
     -H "X-Killbill-CreatedBy: Nick Em" \
     -X POST \
     --data-binary '{"name":"John Doe","email":"john.doe@example.com","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts"
```
So, there is out - that is client library issue.

**Comment by NickEm** [comment]
OK, moving to library 0.40.10 has fixed the compatibility issue.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
